# Generated by Django 6.0.5 on 2026-05-08 18:49

import produtos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[produtos.models.validar_preco_positivo]),
        ),
    ]
