# Generated by Django 6.0.5 on 2026-05-06 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_produto_venda_itemvenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvenda',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='itemvenda',
            name='venda',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='ItemVenda',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
